### ISSUE TITLE
Do you have a tutorial?

### ISSUE THREAD

**Issue by bivvt** [BastienBoymond/korea-concert-ticket-bot#4]
Hello, I'm not a code person. But I really want to use this ticket bot. I'm trying to find a way to code it on a Mac and use it. But it still doesn't work. Do you have a tutorial for downloading and setting it up? I don't know if I'm asking too much or not. I'm sorry if it bothers you. Thank you very much🙇🏻‍♀️

**Comment by bivvt** [comment]
I mean yes24 doesn't even work. After setting it up and pressing start, it doesn't do any work🥲

**Comment by BastienBoymond** [comment]
Hey,
Yes24 work before but is no longer supported i wil need to do few modification
If you are a develloper you can help me on this otherwise i will tell you went feature is done

**Comment by bivvt** [comment]
Okay, I see. I can only take a quick look. I'm really sorry I couldn't help. If I can, I'd like to help you, but my knowledge is only at the high school level. Oh, I also tested interpark. But it doesn't work either. Is this website not supported?

**Comment by symofdes** [comment]
It has minimum two problems
1) in different concerts halls sometimes different name value, somewhere it is map_ticket, somewhere like in your code
2) another thing when script found place the button "seat selection completed" doesn't work because of Content Security Policy, and function from javascript from the website couldn't be chosen. But I'm not js developer, i tried to solve it with chatgpt, but unfortunatelly there is no result

**Comment by BastienBoymond** [comment]
I close this ticket to refer to this one:  #2
